apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tulasi-foods
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
    targetRevision: gcp
    path: helm/tulasi-foods
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: tulasi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
