apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/hydrate: normal
    argocd.argoproj.io/tracking-id: tulasi-foods:argoproj.io/Application:argocd/tulasi-foods
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"tulasi-foods:argoproj.io/Application:argocd/tulasi-foods"},"name":"tulasi-foods","namespace":"argocd"},"spec":{"destination":{"namespace":"tulasi-foods","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"k8s","repoURL":"https://github.com/nareshbaburoddam/tulasi_foods_claude.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2026-08-14T17:43:17Z"
  generation: 3453
  name: tulasi-foods
  namespace: argocd
  resourceVersion: "2984979"
  uid: 3357a112-72c3-4030-a228-2a9f22bc30c2
spec:
  destination:
    namespace: tulasi-foods
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-08-20T05:11:36Z"
    status: Healthy
  history:
  - deployStartedAt: "2026-08-19T04:52:37Z"
    deployedAt: "2026-08-19T04:52:41Z"
    id: 24
    initiatedBy:
      automated: true
    revision: 89df5f06755f9d3cd065423b5af19d203e801642
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-19T05:06:31Z"
    deployedAt: "2026-08-19T05:06:32Z"
    id: 25
    initiatedBy:
      automated: true
    revision: 502be43a3ea4ceb90ec779dc22e7af923b4cf11e
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-19T05:10:47Z"
    deployedAt: "2026-08-19T05:10:48Z"
    id: 26
    initiatedBy:
      automated: true
    revision: e2d6790a990788a7e83a4a0b89c1db1f2a70024d
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-19T05:11:47Z"
    deployedAt: "2026-08-19T05:11:48Z"
    id: 27
    initiatedBy:
      username: admin
    revision: e2d6790a990788a7e83a4a0b89c1db1f2a70024d
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-19T05:27:54Z"
    deployedAt: "2026-08-19T05:27:55Z"
    id: 28
    initiatedBy:
      username: admin
    revision: e2d6790a990788a7e83a4a0b89c1db1f2a70024d
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-19T15:49:09Z"
    deployedAt: "2026-08-19T15:49:10Z"
    id: 29
    initiatedBy:
      automated: true
    revision: 335c285caee049fe6b7f54c74f862f25aebe3945
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-19T17:26:08Z"
    deployedAt: "2026-08-19T17:26:09Z"
    id: 30
    initiatedBy:
      automated: true
    revision: 5d73387b261d8caa587952ae86d194288253083f
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-19T17:26:57Z"
    deployedAt: "2026-08-19T17:26:58Z"
    id: 31
    initiatedBy:
      automated: true
    revision: 0012276fcb2fdb946ab4a2914351b5e9bbe6d43d
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-20T05:09:02Z"
    deployedAt: "2026-08-20T05:09:03Z"
    id: 32
    initiatedBy:
      automated: true
    revision: 1dceac7c99f45a50c5be34b00e79d1275ac2d3fa
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  - deployStartedAt: "2026-08-20T05:27:08Z"
    deployedAt: "2026-08-20T05:27:09Z"
    id: 33
    initiatedBy:
      automated: true
    revision: 1f6fdf15758a5e91a341e807557be023b33d6355
    source:
      path: k8s
      repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
      targetRevision: main
  operationState:
    finishedAt: "2026-08-20T05:27:09Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 1f6fdf15758a5e91a341e807557be023b33d6355
        source:
          path: k8s
          repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
          targetRevision: main
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2026-08-20T05:27:08Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/tulasi-foods unchanged
        name: tulasi-foods
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/tulasi-backend-sa unchanged
        name: tulasi-backend-sa
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: ConfigMap
        message: configmap/nginx-conf unchanged
        name: nginx-conf
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/nginx unchanged
        name: nginx
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/backend unchanged
        name: backend
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - ghcr.io/nareshbaburoddam/tulasi-frontend:1.0.2.1
        kind: Deployment
        message: deployment.apps/nginx unchanged
        name: nginx
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - ghcr.io/nareshbaburoddam/tulasi-backend:1.5.1.10
        kind: Deployment
        message: deployment.apps/backend unchanged
        name: backend
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/nginx-hpa unchanged
        name: nginx-hpa
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v2
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/backend-hpa unchanged
        name: backend-hpa
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v2
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/argocd-ingress unchanged
        name: argocd-ingress
        namespace: argocd
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/tulasi-ingress unchanged
        name: tulasi-ingress
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: azmonitoring.coreos.com
        hookPhase: Running
        kind: PodMonitor
        message: podmonitor.azmonitoring.coreos.com/backend-podmonitor created
        name: backend-podmonitor
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      - group: argoproj.io
        hookPhase: Running
        kind: Application
        message: application.argoproj.io/tulasi-foods unchanged
        name: tulasi-foods
        namespace: argocd
        status: Synced
        syncPhase: Sync
        version: v1alpha1
      - group: secrets-store.csi.x-k8s.io
        hookPhase: Running
        kind: SecretProviderClass
        message: secretproviderclass.secrets-store.csi.x-k8s.io/tulasi-kv-secrets
          unchanged
        name: tulasi-kv-secrets
        namespace: tulasi-foods
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 1f6fdf15758a5e91a341e807557be023b33d6355
      source:
        path: k8s
        repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
        targetRevision: main
  reconciledAt: "2026-08-21T06:38:49Z"
  resourceHealthSource: appTree
  resources:
  - kind: ConfigMap
    name: nginx-conf
    namespace: tulasi-foods
    status: Synced
    version: v1
  - kind: Namespace
    name: tulasi-foods
    status: Synced
    version: v1
  - kind: Service
    name: backend
    namespace: tulasi-foods
    status: Synced
    version: v1
  - kind: Service
    name: nginx
    namespace: tulasi-foods
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: tulasi-backend-sa
    namespace: tulasi-foods
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: backend
    namespace: tulasi-foods
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: nginx
    namespace: tulasi-foods
    status: Synced
    version: v1
  - group: argoproj.io
    kind: Application
    name: tulasi-foods
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    name: backend-hpa
    namespace: tulasi-foods
    status: Synced
    version: v2
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    name: nginx-hpa
    namespace: tulasi-foods
    status: Synced
    version: v2
  - group: azmonitoring.coreos.com
    kind: PodMonitor
    name: backend-podmonitor
    namespace: tulasi-foods
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: Ingress
    name: argocd-ingress
    namespace: argocd
    status: Synced
    version: v1
  - group: networking.k8s.io
    kind: Ingress
    name: tulasi-ingress
    namespace: tulasi-foods
    status: Synced
    version: v1
  - group: secrets-store.csi.x-k8s.io
    kind: SecretProviderClass
    name: tulasi-kv-secrets
    namespace: tulasi-foods
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Directory
  summary:
    externalURLs:
    - https://argocd.nareshroddam.in/
    - https://chaats.nareshroddam.in/
    images:
    - ghcr.io/nareshbaburoddam/tulasi-backend:1.5.1.10
    - ghcr.io/nareshbaburoddam/tulasi-frontend:1.0.2.1
    isAppOfApps: true
  sync:
    comparedTo:
      destination:
        namespace: tulasi-foods
        server: https://kubernetes.default.svc
      source:
        path: k8s
        repoURL: https://github.com/nareshbaburoddam/tulasi_foods_claude.git
        targetRevision: main
    revision: 1f6fdf15758a5e91a341e807557be023b33d6355
    status: Synced
