apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store

spec:
  provider:
    gcpsm:
      projectID: project-33d9f6d4-0170-4924-9fb
      auth:
        workloadIdentity:
          clusterLocation: asia-south1
          clusterName: terraform-gke
          serviceAccountRef:
            name: eso-sa
            namespace: external-secrets
