namespace: bluegreen-lab
color: blue
activeColor: blue
serviceAccountName: tulasi-backend-sa
imagePullSecret: ghcr-pull-secret
secretProviderClass: tulasi-kv-secrets
allowedOrigin: https://bluegreen.nareshroddam.in
backend:
  image:
    repository: ghcr.io/nareshbaburoddam/tulasi-backend
    tag: "1.0.0.15"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  strategy:
    maxSurge: 0
    maxUnavailable: 1
hpa:
  minReplicas: 1
  maxReplicas: 2
podMonitor:
  enabled: false
frontend:
  image:
    repository: ghcr.io/nareshbaburoddam/tulasi-frontend
    tag: "1.0.0.2"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  strategy:
    maxSurge: 0
    maxUnavailable: 1
ingress:
  host: bluegreen.nareshroddam.in
  tlsSecret: tulasi-tls
workloadIdentity:
  clientId: "88113289-689c-4795-99ad-4727a99eb8eb"
azure:
  keyVaultName: "tulasi-kv-2026"
  tenantId: "e41f5746-929e-4d11-a6ab-d553e45ed8c3"
hpa:
  minReplicas: 1
  maxReplicas: 2
  cpuTargetUtilization: 70
