namespace: tulasi
color: blue
activeColor: blue
serviceAccountName: tulasi-backed-sa
imagePullSecret: ghcr-pull-secret
secretProviderClass: tulasi-kv-secrets
allowedOrigin: https://bluegreen.nareshroddam.in
backend:
  image:
    repository: ghcr.io/nareshbaburoddam/tulasi-backend
    tag: "1.0.0.17"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  strategy:
    maxSurge: 0
    maxUnavailable: 1
hpa:
  minReplicas: 1
  maxReplicas: 2
podMonitor:
  enabled: false
frontend:
  image:
    repository: ghcr.io/nareshbaburoddam/tulasi-frontend
    tag: "1.0.0.5"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  strategy:
    maxSurge: 0
    maxUnavailable: 1
ingress:
  host: bluegreen.nareshroddam.in
  tlsSecret: tulasi-tls
hpa:
  minReplicas: 1
  maxReplicas: 2
  cpuTargetUtilization: 70
