apiVersion: azmonitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: backend-podmonitor
  namespace: tulasi-foods
spec:
  selector:
    matchLabels:
      app: backend
  podMetricsEndpoints:
  - targetPort: 8000
    path: /metrics
    interval: 30s
