apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ .Values.color }}
  namespace: {{ .Values.namespace }}

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.backend.strategy.maxSurge }}
      maxUnavailable: {{ .Values.backend.strategy.maxUnavailable }}

  selector:
    matchLabels:
      app: backend
      version: {{ .Values.color }}

  template:
    metadata:
      labels:
        app: backend
        version: {{ .Values.color }}

    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}

      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: backend
                topologyKey: kubernetes.io/hostname

      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          ports:
            - containerPort: 8000

          resources:
{{- toYaml .Values.backend.resources | nindent 12 }}

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tulasi-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tulasi-secrets
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: tulasi-secrets
                  key: POSTGRES_DB

            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: tulasi-secrets
                  key: POSTGRES_HOST

            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tulasi-secrets
                  key: SECRET_KEY

            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tulasi-secrets
                  key: ADMIN_USERNAME

            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tulasi-secrets
                  key: ADMIN_PASSWORD

            - name: ALLOWED_ORIGIN
              value: "{{ .Values.allowedOrigin }}"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
