{{- if eq .Values.color "green" }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tulasi-canary-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"

spec:
  ingressClassName: webapprouting.kubernetes.azure.com

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-green
                port:
                  number: 80

{{- end }}
