apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tulasi-secrets
  namespace: tulasi

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: tulasi-secrets

  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: POSTGRES_PASSWORD

    - secretKey: POSTGRES_DB
      remoteRef:
        key: POSTGRES_DB

    - secretKey: POSTGRES_HOST
      remoteRef:
        key: POSTGRES_HOST

    - secretKey: SECRET_KEY
      remoteRef:
        key: SECRET_KEY

    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: ADMIN_USERNAME

    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: ADMIN_PASSWORD
