apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tulasi
  namespace: {{ .Values.namespace }}

spec:
  entryPoints:
    - web
    - websecure

  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: nginx-wrr
          kind: TraefikService

  tls:
    secretName: {{ .Values.ingress.tlsSecret }}
