{{- if .Values.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.canary.replicas | default 1 }}
  selector:
    matchLabels:
      app: nginx
      version: canary
  template:
    metadata:
      labels:
        app: nginx
        version: canary
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: nginx
          image: "{{ .Values.canary.image.repository }}:{{ .Values.canary.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/tulasi.conf
              subPath: tulasi.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf-{{ .Values.color }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-canary
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx
    version: canary
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}
