apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  #replicas: 2
    strategy:
    rollingUpdate:
      maxSurge: {{ .Values.frontend.strategy.maxSurge }}        # never create a NEW pod before an OLD one is gone
      maxUnavailable: {{ .Values.frontend.strategy.maxUnavailable }}   # replace one pod at a time
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: nginx
                topologyKey: kubernetes.io/hostname
      containers:
        - name: nginx
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
          resources:
          {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/tulasi.conf
              subPath: tulasi.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf

