{{- range $color := list "blue" "green" }}
{{- $colorConfig := index $.Values.frontend $color }}
{{- if $colorConfig.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ $color }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ $colorConfig.replicas | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ $.Values.frontend.strategy.maxSurge }}
      maxUnavailable: {{ $.Values.frontend.strategy.maxUnavailable }}
  selector:
    matchLabels:
      app: nginx
      version: {{ $color }}
  template:
    metadata:
      labels:
        app: nginx
        version: {{ $color }}
    spec:
      imagePullSecrets:
        - name: {{ $.Values.imagePullSecret }}
      containers:
        - name: nginx
          image: "{{ $colorConfig.image.repository }}:{{ $colorConfig.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml $.Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/tulasi.conf
              subPath: tulasi.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf-blue
---
{{- end }}
{{- end }}
