apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: nginx-wrr
  namespace: {{ .Values.namespace }}
spec:
  weighted:
    services:
      - name: nginx-stable
        port: 80
        weight: 100
      - name: nginx-canary
        port: 80
        weight: 0
