{{- if eq .Values.color "blue" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.workloadIdentity.clientId }}"
{{- end }}
